server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.bqd.data.dao
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml